[package]
name = "dev-cli"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "dev"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.96"
clap = { version = "4.5", features = ["derive"] }
console = "0.15.8"
ctrlc = "3.4.5"
dialoguer = { version = "0.11.0", features = ["fuzzy-select"] }
dirs = "5.0"
regex = "1.11"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9.34"
toml = "0.8"
glob = "0.3"
which = "7.0.2"
dotenvy = "0.15"
fuzzy-matcher = "0.3"
indicatif = "0.18.3"
